//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineBooking.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ARS_AIRLINESEntities1 : DbContext
    {
        public ARS_AIRLINESEntities1()
            : base("name=ARS_AIRLINESEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AVAILABLE_FLIGHT_CITIES> AVAILABLE_FLIGHT_CITIES { get; set; }
        public DbSet<FLIGHT_AVAILABLITY> FLIGHT_AVAILABLITY { get; set; }
        public DbSet<FLIGHT_CLASS> FLIGHT_CLASS { get; set; }
        public DbSet<FLIGHT_RESERVATION> FLIGHT_RESERVATION { get; set; }
        public DbSet<SEX> SEXes { get; set; }
        public DbSet<TRIP_TYPE> TRIP_TYPE { get; set; }
        public DbSet<USER> USERs { get; set; }
        public DbSet<FLIGHT_SCHEDULE> FLIGHT_SCHEDULE { get; set; }
    }
}
