//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineBooking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLIGHT_RESERVATION
    {
        public int Id { get; set; }
        public int FlightId { get; set; }
        public int UserId { get; set; }
        public string Status { get; set; }
        public string BlockingNumber { get; set; }
        public string CancellationNumber { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual FLIGHT_SCHEDULE FLIGHT_SCHEDULE { get; set; }
    }
}
