//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineBooking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public USER()
        {
            this.FLIGHT_RESERVATION = new HashSet<FLIGHT_RESERVATION>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public int SexId { get; set; }
        public int Age { get; set; }
        public string CreditCardNumber { get; set; }
        public int FlyMiles { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ICollection<FLIGHT_RESERVATION> FLIGHT_RESERVATION { get; set; }
        public virtual SEX SEX { get; set; }
    }
}
